"""Supabase Storage backend (production object storage).

Uses Supabase's Storage REST API directly through httpx (already a backend
runtime dependency for email/AI/provider integrations). The service-role key is
server-only and never exposed to clients. Object keys are generated by the
application (`documents/{owner}/{document}/source`) and validated here as a
second guardrail: user-controlled filenames never become storage paths.
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

import httpx

_REQUEST_TIMEOUT_S = 20.0
_RESPONSE_MAX_BYTES = 20 * 1024 * 1024


class SupabaseStorageBackend:
    """Supabase Storage implementation of the StorageBackend protocol."""

    def __init__(self, *, url: str, service_role_key: str, bucket: str) -> None:
        self._base_url = url.rstrip("/")
        self._service_role_key = service_role_key
        self._bucket = bucket.strip()
        if not self._base_url or not self._service_role_key or not self._bucket:
            raise RuntimeError("Supabase storage is not configured.")

    def _headers(self, *, content_type: str | None = None) -> dict[str, str]:
        headers = {
            "Authorization": f"Bearer {self._service_role_key}",
            "apikey": self._service_role_key,
        }
        if content_type is not None:
            headers["Content-Type"] = content_type
        return headers

    def _safe_key(self, key: str) -> str:
        if not key or key.startswith("/") or "\\" in key:
            raise ValueError(f"refusing unsafe storage key: {key!r}")
        parts = key.split("/")
        if any(part in {"", ".", ".."} for part in parts):
            raise ValueError(f"refusing unsafe storage key: {key!r}")
        return quote(key, safe="/")

    def _object_url(self, key: str) -> str:
        safe_key = self._safe_key(key)
        return f"{self._base_url}/storage/v1/object/{self._bucket}/{safe_key}"

    def store_file(self, key: str, src: Path) -> None:
        with src.open("rb") as handle:
            with httpx.Client(timeout=_REQUEST_TIMEOUT_S, follow_redirects=False) as client:
                response = client.post(
                    self._object_url(key),
                    headers={
                        **self._headers(content_type="application/octet-stream"),
                        "x-upsert": "false",
                    },
                    content=handle,
                )
        if 200 <= response.status_code < 300:
            src.unlink(missing_ok=True)
            return
        raise RuntimeError("Supabase storage upload failed.")

    def delete(self, key: str) -> None:
        safe_key = self._safe_key(key)
        with httpx.Client(timeout=_REQUEST_TIMEOUT_S, follow_redirects=False) as client:
            response = client.request(
                "DELETE",
                f"{self._base_url}/storage/v1/object/{self._bucket}",
                headers=self._headers(content_type="application/json"),
                json={"prefixes": [safe_key]},
            )
        if response.status_code in {200, 204, 404}:
            return
        raise RuntimeError("Supabase storage delete failed.")

    def read_bytes(self, key: str) -> bytes:
        with httpx.Client(timeout=_REQUEST_TIMEOUT_S, follow_redirects=False) as client:
            response = client.get(self._object_url(key), headers=self._headers())
        if response.status_code == 404:
            raise FileNotFoundError(key)
        if response.status_code < 200 or response.status_code >= 300:
            raise RuntimeError("Supabase storage read failed.")
        if len(response.content) > _RESPONSE_MAX_BYTES:
            raise RuntimeError("Supabase storage object exceeded response cap.")
        return bytes(response.content)
