// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

import { AiOverviewSection } from "./AiOverviewSection";

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function errorResponse(code: string, status: number): Response {
  return jsonResponse({ error: { code, message: "Server copy (never displayed)." } }, status);
}

afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe("AiOverviewSection", () => {
  it("skipped renders a neutral note with no heading and no CTA", () => {
    const { container } = render(
      <AiOverviewSection status="skipped" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByText("AI enhancement was off for this run — deterministic results only."),
    ).toBeDefined();
    expect(container.querySelector("h3")).toBeNull();
    expect(container.querySelector("a")).toBeNull();
  });

  it("unconfigured renders the empty state with a Settings CTA", () => {
    render(
      <AiOverviewSection status="unconfigured" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByRole("heading", { name: "AI enhancement isn't configured yet" }),
    ).toBeDefined();
    const cta = screen.getByRole("link", { name: "Open Settings" });
    expect(cta.getAttribute("href")).toBe("/settings");
  });

  it("failed renders the user-safe error verbatim with no retry button", () => {
    const { container } = render(
      <AiOverviewSection
        status="failed"
        overview={null}
        provider={null}
        error="Quota exceeded. Try again later."
      />,
    );
    expect(screen.getByRole("heading", { name: "AI enhancement failed" })).toBeDefined();
    expect(screen.getByText("Quota exceeded. Try again later.")).toBeDefined();
    expect(screen.getByText(/unaffected/)).toBeDefined();
    expect(container.querySelector("button")).toBeNull(); // no retry prop, no button
  });

  it("ok renders the labeled overview with provider attribution", () => {
    render(
      <AiOverviewSection
        status="ok"
        overview="Overall solid; tighten the vague bounds."
        provider="groq"
        error={null}
      />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Generated by Groq")).toBeDefined();
    expect(screen.getByText("Overall solid; tighten the vague bounds.")).toBeDefined();
  });

  it("ok with an unknown provider degrades to unattributed rendering", () => {
    const { container } = render(
      <AiOverviewSection status="ok" overview="Overview text." provider="skynet" error={null} />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Overview text.")).toBeDefined();
    expect(container.textContent).not.toContain("Generated by");
  });

  it("renders model output as inert text (markup never interprets)", () => {
    const { container } = render(
      <AiOverviewSection
        status="ok"
        overview="<script>alert('xss')</script> & <b>bold</b>"
        provider="openai"
        error={null}
      />,
    );
    expect(container.querySelector("script")).toBeNull();
    expect(container.querySelector("b")).toBeNull();
    expect(screen.getByText("<script>alert('xss')</script> & <b>bold</b>")).toBeDefined();
  });

  it("ok carries an explicit review disclaimer", () => {
    render(<AiOverviewSection status="ok" overview="Overview." provider="groq" error={null} />);
    expect(
      screen.getByText(/AI-generated enrichment — review suggestions against the original/),
    ).toBeDefined();
  });

  it("long overviews clamp behind an accessible Show more/less disclosure", async () => {
    const user = userEvent.setup();
    const long = `Summary. ${"x".repeat(700)}`;
    const { container } = render(
      <AiOverviewSection status="ok" overview={long} provider="groq" error={null} />,
    );
    const toggle = screen.getByRole("button", { name: "Show more" });
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    expect(container.querySelector("p.line-clamp-6")).not.toBeNull();
    await user.click(toggle);
    expect(screen.getByRole("button", { name: "Show less" }).getAttribute("aria-expanded")).toBe(
      "true",
    );
    expect(container.querySelector("p.line-clamp-6")).toBeNull();
  });

  it("short overviews render fully with no disclosure", () => {
    const { container } = render(
      <AiOverviewSection status="ok" overview="Short." provider="groq" error={null} />,
    );
    expect(container.querySelector("button")).toBeNull();
    expect(container.querySelector("p.line-clamp-6")).toBeNull();
  });

  it("partial rewrite coverage renders the honest derived note", () => {
    render(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 7, flagged: 10 }}
      />,
    );
    expect(screen.getByText("AI rewrites cover 7 of 10 flagged requirements.")).toBeDefined();
  });

  it("complete or empty coverage renders no note", () => {
    const { rerender, container } = render(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 3, flagged: 3 }}
      />,
    );
    expect(container.textContent).not.toContain("AI rewrites cover");
    rerender(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 0, flagged: 0 }}
      />,
    );
    expect(container.textContent).not.toContain("AI rewrites cover");
  });
});

describe("AiOverviewSection retry (Stage 17)", () => {
  const RETRY = {
    ai_status: "ok",
    ai_overview: "Fresh overview.",
    ai_provider: "groq",
    ai_error: null,
  };

  function renderFailed(retry: { analysisId: string; onRetried: () => Promise<unknown> } | null) {
    return render(
      <AiOverviewSection
        status="failed"
        overview={null}
        provider={null}
        error="Provider timed out."
        retry={retry}
      />,
    );
  }

  it("renders no button without retry wiring (existing behavior preserved)", () => {
    const { container } = renderFailed(null);
    expect(container.querySelector("button")).toBeNull();
  });

  it("posts the retry, then refreshes the parent record", async () => {
    const user = userEvent.setup();
    const seen: Array<{ url: string; method: string }> = [];
    const onRetried = vi.fn(async () => undefined);
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
        seen.push({ url: String(input), method: init?.method ?? "GET" });
        return jsonResponse(RETRY);
      }),
    );
    renderFailed({ analysisId: "analysis-9", onRetried });
    await user.click(screen.getByRole("button", { name: "Try again" }));
    await vi.waitFor(() => expect(onRetried).toHaveBeenCalledTimes(1));
    expect(seen).toEqual([
      { url: expect.stringContaining("/analysis/analysis-9/retry-ai"), method: "POST" },
    ]);
  });

  it("pending disables the button with Retrying copy (no double POST)", async () => {
    const user = userEvent.setup();
    let release!: (response: Response) => void;
    const gate = new Promise<Response>((resolve) => {
      release = resolve;
    });
    let posts = 0;
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => {
        posts += 1;
        return gate;
      }),
    );
    renderFailed({ analysisId: "analysis-9", onRetried: async () => undefined });
    const button = screen.getByRole("button", { name: "Try again" });
    await user.click(button);
    expect((screen.getByRole("button", { name: "Retrying…" }) as HTMLButtonElement).disabled).toBe(
      true,
    );
    await user.click(screen.getByRole("button", { name: "Retrying…" }));
    release(jsonResponse(RETRY));
    await screen.findByRole("button", { name: "Try again" });
    expect(posts).toBe(1);
  });

  it("a refused retry stays on the card with code-mapped copy", async () => {
    const user = userEvent.setup();
    const onRetried = vi.fn(async () => undefined);
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => errorResponse("rate_limited", 429)),
    );
    renderFailed({ analysisId: "analysis-9", onRetried });
    await user.click(screen.getByRole("button", { name: "Try again" }));
    expect(
      await screen.findByText("Too many requests. Please wait a moment and try again."),
    ).toBeDefined();
    expect(onRetried).not.toHaveBeenCalled();
    // Still retryable: the button is back, the deterministic note intact.
    expect(screen.getByRole("button", { name: "Try again" })).toBeDefined();
    expect(screen.getByText(/unaffected/)).toBeDefined();
  });

  it("a dead session offers sign-in instead of a blind retry", async () => {
    const user = userEvent.setup();
    const onRetried = vi.fn(async () => undefined);
    vi.stubGlobal(
      "fetch",
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);
        if (url.includes("/auth/refresh")) return errorResponse("unauthenticated", 401);
        return errorResponse("unauthenticated", 401);
      }),
    );
    renderFailed({ analysisId: "analysis-9", onRetried });
    await user.click(screen.getByRole("button", { name: "Try again" }));
    expect(await screen.findByText(/session expired before the retry finished/)).toBeDefined();
    expect(screen.getByRole("link", { name: "Sign in again" }).getAttribute("href")).toBe("/login");
    expect(onRetried).not.toHaveBeenCalled();
  });

  it("a failed parent refresh surfaces mapped copy (retry landed, view stale)", async () => {
    const user = userEvent.setup();
    vi.stubGlobal(
      "fetch",
      vi.fn(async () => jsonResponse(RETRY)),
    );
    const { ApiRequestError } = await import("@/lib/api");
    const onRetried = vi.fn(async () => {
      throw new ApiRequestError(500, { code: "internal_error", message: "nope" });
    });
    renderFailed({ analysisId: "analysis-9", onRetried });
    await user.click(screen.getByRole("button", { name: "Try again" }));
    expect(await screen.findByText("Something went wrong. Please try again.")).toBeDefined();
  });
});
