// @vitest-environment jsdom
import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";

import { AiOverviewSection } from "./AiOverviewSection";

afterEach(() => {
  cleanup();
});

describe("AiOverviewSection", () => {
  it("skipped renders a neutral note with no heading and no CTA", () => {
    const { container } = render(
      <AiOverviewSection status="skipped" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByText("AI enhancement was off for this run — deterministic results only."),
    ).toBeDefined();
    expect(container.querySelector("h3")).toBeNull();
    expect(container.querySelector("a")).toBeNull();
  });

  it("unconfigured renders the empty state with a Settings CTA", () => {
    render(
      <AiOverviewSection status="unconfigured" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByRole("heading", { name: "AI enhancement isn't configured yet" }),
    ).toBeDefined();
    const cta = screen.getByRole("link", { name: "Open Settings" });
    expect(cta.getAttribute("href")).toBe("/settings");
  });

  it("failed renders the user-safe error verbatim with no retry button", () => {
    const { container } = render(
      <AiOverviewSection
        status="failed"
        overview={null}
        provider={null}
        error="Quota exceeded. Try again later."
      />,
    );
    expect(screen.getByRole("heading", { name: "AI enhancement failed" })).toBeDefined();
    expect(screen.getByText("Quota exceeded. Try again later.")).toBeDefined();
    expect(screen.getByText(/unaffected/)).toBeDefined();
    expect(container.querySelector("button")).toBeNull(); // retry-ai is a later stage
  });

  it("ok renders the labeled overview with provider attribution", () => {
    render(
      <AiOverviewSection
        status="ok"
        overview="Overall solid; tighten the vague bounds."
        provider="groq"
        error={null}
      />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Generated by Groq")).toBeDefined();
    expect(screen.getByText("Overall solid; tighten the vague bounds.")).toBeDefined();
  });

  it("ok with an unknown provider degrades to unattributed rendering", () => {
    const { container } = render(
      <AiOverviewSection status="ok" overview="Overview text." provider="skynet" error={null} />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Overview text.")).toBeDefined();
    expect(container.textContent).not.toContain("Generated by");
  });

  it("renders model output as inert text (markup never interprets)", () => {
    const { container } = render(
      <AiOverviewSection
        status="ok"
        overview="<script>alert('xss')</script> & <b>bold</b>"
        provider="openai"
        error={null}
      />,
    );
    expect(container.querySelector("script")).toBeNull();
    expect(container.querySelector("b")).toBeNull();
    expect(screen.getByText("<script>alert('xss')</script> & <b>bold</b>")).toBeDefined();
  });
});
