"use client";

/**
 * AI enhancement outcome block (Stage 14): one of four honest states driven
 * by `ai_status` — generated overview with provider attribution (`ok`),
 * user-safe error card (`failed` — deterministic findings stay visible, NO
 * retry button: `retry-ai` is a later stage), empty state + Settings CTA
 * (`unconfigured`), or a neutral one-liner (`skipped`). Renders nothing
 * structural the deterministic report depends on: AI is additive-only.
 *
 * Text discipline: `overview`/`error` render as PLAIN TEXT (React-escaped —
 * model output is untrusted by contract). Unknown provider ids degrade to
 * unattributed rendering (drift never crashes the report).
 */

import Link from "next/link";
import { Bot, CircleAlert, Settings2 } from "lucide-react";

import type { AiStatus } from "@/types/analysis";
import { PROVIDER_DISPLAY_NAMES, isProviderId } from "@/types/providers";

function attribution(provider: string | null): string | null {
  if (!isProviderId(provider)) return null;
  return PROVIDER_DISPLAY_NAMES[provider];
}

export function AiOverviewSection({
  status,
  overview,
  provider,
  error,
}: {
  status: AiStatus;
  overview: string | null;
  provider: string | null;
  error: string | null;
}) {
  if (status === "skipped") {
    return (
      <p role="status" className="mt-6 font-mono text-xs text-ink-faint">
        AI enhancement was off for this run — deterministic results only.
      </p>
    );
  }

  if (status === "unconfigured") {
    return (
      <div className="mt-6 rounded-card border border-dashed border-line bg-paper p-5 sm:p-6">
        <div className="flex items-start gap-3">
          <Bot className="mt-0.5 size-5 shrink-0 text-ink-faint" aria-hidden />
          <div>
            <h3 className="text-[15px] font-semibold">AI enhancement isn&apos;t configured yet</h3>
            <p className="mt-1 text-sm leading-relaxed text-ink-soft">
              Add your own provider key to get an AI-written overview plus per-requirement rewrites
              on future runs. Deterministic scores and issues work without it.
            </p>
            <Link
              href="/settings"
              className="mt-3 inline-flex items-center gap-1.5 rounded-full border border-line px-4 py-1.5 text-sm font-medium text-ink-soft transition hover:bg-paper-deep"
            >
              <Settings2 className="size-4" aria-hidden />
              Open Settings
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (status === "failed") {
    return (
      <div className="mt-6 rounded-card border border-critic/40 bg-paper p-5 sm:p-6">
        <div className="flex items-start gap-3">
          <CircleAlert className="mt-0.5 size-5 shrink-0 text-critic" aria-hidden />
          <div>
            <h3 className="text-[15px] font-semibold">AI enhancement failed</h3>
            <p className="mt-1 text-sm leading-relaxed text-ink-soft">
              {error ?? "The AI step did not complete."}
            </p>
            <p className="mt-2 text-[13px] leading-relaxed text-ink-faint">
              Deterministic scores and issues above are unaffected — only the AI overview and
              rewrites are missing.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const byline = attribution(provider);
  return (
    <div className="mt-6 rounded-card border border-line bg-paper p-5 sm:p-6">
      <div className="flex items-start gap-3">
        <Bot className="mt-0.5 size-5 shrink-0 text-signal" aria-hidden />
        <div className="min-w-0">
          <h3 className="text-[15px] font-semibold">AI overview</h3>
          {byline ? (
            <p className="mt-0.5 font-mono text-xs text-ink-faint">Generated by {byline}</p>
          ) : null}
          <p className="mt-2 text-[15px] leading-relaxed whitespace-pre-wrap text-ink-soft">
            {overview ?? "No overview text was returned."}
          </p>
        </div>
      </div>
    </div>
  );
}
