// @vitest-environment jsdom
import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";

import { AiOverviewSection } from "./AiOverviewSection";

afterEach(() => {
  cleanup();
});

describe("AiOverviewSection", () => {
  it("skipped renders a neutral note with no heading and no CTA", () => {
    const { container } = render(
      <AiOverviewSection status="skipped" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByText("AI enhancement was off for this run — deterministic results only."),
    ).toBeDefined();
    expect(container.querySelector("h3")).toBeNull();
    expect(container.querySelector("a")).toBeNull();
  });

  it("unconfigured renders the empty state with a Settings CTA", () => {
    render(
      <AiOverviewSection status="unconfigured" overview={null} provider={null} error={null} />,
    );
    expect(
      screen.getByRole("heading", { name: "AI enhancement isn't configured yet" }),
    ).toBeDefined();
    const cta = screen.getByRole("link", { name: "Open Settings" });
    expect(cta.getAttribute("href")).toBe("/settings");
  });

  it("failed renders the user-safe error verbatim with no retry button", () => {
    const { container } = render(
      <AiOverviewSection
        status="failed"
        overview={null}
        provider={null}
        error="Quota exceeded. Try again later."
      />,
    );
    expect(screen.getByRole("heading", { name: "AI enhancement failed" })).toBeDefined();
    expect(screen.getByText("Quota exceeded. Try again later.")).toBeDefined();
    expect(screen.getByText(/unaffected/)).toBeDefined();
    expect(container.querySelector("button")).toBeNull(); // retry-ai is a later stage
  });

  it("ok renders the labeled overview with provider attribution", () => {
    render(
      <AiOverviewSection
        status="ok"
        overview="Overall solid; tighten the vague bounds."
        provider="groq"
        error={null}
      />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Generated by Groq")).toBeDefined();
    expect(screen.getByText("Overall solid; tighten the vague bounds.")).toBeDefined();
  });

  it("ok with an unknown provider degrades to unattributed rendering", () => {
    const { container } = render(
      <AiOverviewSection status="ok" overview="Overview text." provider="skynet" error={null} />,
    );
    expect(screen.getByRole("heading", { name: "AI overview" })).toBeDefined();
    expect(screen.getByText("Overview text.")).toBeDefined();
    expect(container.textContent).not.toContain("Generated by");
  });

  it("renders model output as inert text (markup never interprets)", () => {
    const { container } = render(
      <AiOverviewSection
        status="ok"
        overview="<script>alert('xss')</script> & <b>bold</b>"
        provider="openai"
        error={null}
      />,
    );
    expect(container.querySelector("script")).toBeNull();
    expect(container.querySelector("b")).toBeNull();
    expect(screen.getByText("<script>alert('xss')</script> & <b>bold</b>")).toBeDefined();
  });

  it("ok carries an explicit review disclaimer", () => {
    render(<AiOverviewSection status="ok" overview="Overview." provider="groq" error={null} />);
    expect(
      screen.getByText(/AI-generated enrichment — review suggestions against the original/),
    ).toBeDefined();
  });

  it("long overviews clamp behind an accessible Show more/less disclosure", async () => {
    const user = userEvent.setup();
    const long = `Summary. ${"x".repeat(700)}`;
    const { container } = render(
      <AiOverviewSection status="ok" overview={long} provider="groq" error={null} />,
    );
    const toggle = screen.getByRole("button", { name: "Show more" });
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    expect(container.querySelector("p.line-clamp-6")).not.toBeNull();
    await user.click(toggle);
    expect(screen.getByRole("button", { name: "Show less" }).getAttribute("aria-expanded")).toBe(
      "true",
    );
    expect(container.querySelector("p.line-clamp-6")).toBeNull();
  });

  it("short overviews render fully with no disclosure", () => {
    const { container } = render(
      <AiOverviewSection status="ok" overview="Short." provider="groq" error={null} />,
    );
    expect(container.querySelector("button")).toBeNull();
    expect(container.querySelector("p.line-clamp-6")).toBeNull();
  });

  it("partial rewrite coverage renders the honest derived note", () => {
    render(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 7, flagged: 10 }}
      />,
    );
    expect(screen.getByText("AI rewrites cover 7 of 10 flagged requirements.")).toBeDefined();
  });

  it("complete or empty coverage renders no note", () => {
    const { rerender, container } = render(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 3, flagged: 3 }}
      />,
    );
    expect(container.textContent).not.toContain("AI rewrites cover");
    rerender(
      <AiOverviewSection
        status="ok"
        overview="Overview."
        provider="groq"
        error={null}
        rewriteCoverage={{ rewritten: 0, flagged: 0 }}
      />,
    );
    expect(container.textContent).not.toContain("AI rewrites cover");
  });
});
