"""Initial schema: users, documents, analyses, requirements, issues, ai_provider_credentials.

Revision ID: 0001
Revises: None

Hand-written (not autogenerated): constraint/index names intentionally match
app/models/* so future autogenerate diffs stay clean. Creation order respects
foreign keys (documents before analyses). No extensions required — UUIDs are
generated client-side, emails use VARCHAR (app lowercases).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATED = sa.Column(
    "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
)
_UPDATED = sa.Column(
    "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
)


def _uuid_pk() -> sa.Column:
    return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True)


def _owner_fk() -> sa.Column:
    return sa.Column(
        "owner_id",
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )


def upgrade() -> None:
    op.create_table(
        "users",
        _uuid_pk(),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("display_name", sa.String(100)),
        sa.Column("password_hash", sa.Text),
        sa.Column("identity_provider", sa.String(32), nullable=False, server_default="local"),
        sa.Column("external_subject", sa.Text),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        _CREATED,
        _UPDATED,
    )
    op.create_index(
        "ix_users_idp_subject",
        "users",
        ["identity_provider", "external_subject"],
        unique=True,
        postgresql_where=sa.text("external_subject IS NOT NULL"),
    )

    op.create_table(
        "documents",
        _uuid_pk(),
        _owner_fk(),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("mime_type", sa.String(127), nullable=False),
        sa.Column("byte_size", sa.BigInteger, nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        sa.Column("storage_path", sa.Text, nullable=False),
        sa.Column("extracted_chars", sa.Integer),
        sa.Column("extraction_status", sa.String(16), nullable=False, server_default="pending"),
        _CREATED,
        sa.CheckConstraint("byte_size >= 0", name="ck_documents_byte_size"),
        sa.CheckConstraint("extracted_chars >= 0", name="ck_documents_extracted_chars"),
        sa.CheckConstraint(
            "extraction_status IN ('pending', 'ok', 'failed')",
            name="ck_documents_extraction_status",
        ),
        sa.UniqueConstraint("storage_path", name="uq_documents_storage_path"),
    )
    op.create_index("ix_documents_owner_created", "documents", ["owner_id", "created_at"])

    op.create_table(
        "analyses",
        _uuid_pk(),
        _owner_fk(),
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("documents.id", ondelete="SET NULL"),
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("source_type", sa.String(16), nullable=False),
        sa.Column("source_excerpt", sa.Text),
        sa.Column("score", sa.SmallInteger, nullable=False),
        sa.Column("band", sa.String(16), nullable=False),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB,
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("requirements_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("issues_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("health", postgresql.JSONB),
        sa.Column("ai_overview", sa.Text),
        sa.Column("ai_provider", sa.String(32)),
        sa.Column("ai_status", sa.String(16), nullable=False, server_default="skipped"),
        sa.Column("ai_error", sa.String(300)),
        _CREATED,
        _UPDATED,
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_analyses_score_range"),
        sa.CheckConstraint("source_type IN ('text', 'document')", name="ck_analyses_source_type"),
        sa.CheckConstraint(
            "band IN ('low', 'moderate', 'high', 'very_high')", name="ck_analyses_band"
        ),
        sa.CheckConstraint(
            "ai_status IN ('ok', 'failed', 'skipped', 'unconfigured')",
            name="ck_analyses_ai_status",
        ),
        sa.CheckConstraint("requirements_count >= 0", name="ck_analyses_req_count"),
        sa.CheckConstraint("issues_count >= 0", name="ck_analyses_issue_count"),
    )
    op.create_index("ix_analyses_owner_created", "analyses", ["owner_id", "created_at"])
    op.create_index("ix_analyses_owner_score", "analyses", ["owner_id", "score"])
    op.create_index("ix_analyses_document", "analyses", ["document_id"])

    op.create_table(
        "requirements",
        _uuid_pk(),
        _owner_fk(),
        sa.Column(
            "analysis_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("analyses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer, nullable=False),
        sa.Column("identifier", sa.String(32)),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("score", sa.SmallInteger, nullable=False),
        sa.Column("severity", sa.String(16)),
        sa.Column("issues_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("suggested_rewrite", sa.Text),
        sa.Column("suggestion_source", sa.String(16)),
        _CREATED,
        sa.UniqueConstraint("analysis_id", "position", name="uq_requirements_analysis_position"),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_requirements_score_range"),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name="ck_requirements_severity",
        ),
        sa.CheckConstraint("issues_count >= 0", name="ck_requirements_issue_count"),
        sa.CheckConstraint(
            "suggestion_source IN ('rule', 'ai')", name="ck_requirements_suggestion_source"
        ),
    )
    op.create_index("ix_requirements_owner_analysis", "requirements", ["owner_id", "analysis_id"])

    op.create_table(
        "issues",
        _uuid_pk(),
        _owner_fk(),
        sa.Column(
            "requirement_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("requirements.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "analysis_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("analyses.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("detector_id", sa.String(64), nullable=False),
        sa.Column("category", sa.String(64), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("phrase", sa.Text, nullable=False),
        sa.Column("start_offset", sa.Integer, nullable=False),
        sa.Column("end_offset", sa.Integer, nullable=False),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column("recommendation", sa.Text, nullable=False),
        sa.Column("ai_explanation", sa.Text),
        _CREATED,
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')", name="ck_issues_severity"
        ),
        sa.CheckConstraint("start_offset >= 0", name="ck_issues_start_offset"),
        sa.CheckConstraint("end_offset > start_offset", name="ck_issues_offset_order"),
    )
    op.create_index("ix_issues_analysis_severity", "issues", ["analysis_id", "severity"])
    op.create_index("ix_issues_analysis_category", "issues", ["analysis_id", "category"])
    op.create_index("ix_issues_requirement", "issues", ["requirement_id"])
    op.create_index("ix_issues_owner_created", "issues", ["owner_id", "created_at"])

    op.create_table(
        "ai_provider_credentials",
        _uuid_pk(),
        _owner_fk(),
        sa.Column("provider", sa.String(32), nullable=False),
        sa.Column("label", sa.String(80)),
        sa.Column("encrypted_api_key", sa.Text, nullable=False),
        sa.Column("key_version", sa.SmallInteger, nullable=False, server_default="1"),
        sa.Column("key_fingerprint", sa.CHAR(16), nullable=False),
        sa.Column("last4", sa.CHAR(4), nullable=False),
        sa.Column("is_enabled", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("fallback_rank", sa.SmallInteger, nullable=False, server_default="0"),
        sa.Column("last_tested_at", sa.DateTime(timezone=True)),
        sa.Column("last_test_status", sa.String(16)),
        _CREATED,
        _UPDATED,
        sa.UniqueConstraint(
            "owner_id",
            "provider",
            "key_fingerprint",
            name="uq_ai_cred_owner_provider_fingerprint",
        ),
        sa.CheckConstraint(
            "provider IN ('gemini', 'groq', 'openai', 'anthropic', 'openrouter'," " 'huggingface')",
            name="ck_ai_cred_provider",
        ),
        sa.CheckConstraint("key_version >= 1", name="ck_ai_cred_key_version"),
        sa.CheckConstraint("fallback_rank >= 0", name="ck_ai_cred_fallback_rank"),
        sa.CheckConstraint("last_test_status IN ('ok', 'failed')", name="ck_ai_cred_test_status"),
    )
    op.create_index(
        "ix_ai_cred_owner_fallback", "ai_provider_credentials", ["owner_id", "fallback_rank"]
    )
    op.create_index(
        "uq_ai_cred_default_per_owner",
        "ai_provider_credentials",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_index(
        "uq_ai_cred_enabled_per_provider",
        "ai_provider_credentials",
        ["owner_id", "provider"],
        unique=True,
        postgresql_where=sa.text("is_enabled"),
    )


def downgrade() -> None:
    # Reverse dependency order; DROP TABLE carries its indexes along.
    op.drop_table("ai_provider_credentials")
    op.drop_table("issues")
    op.drop_table("requirements")
    op.drop_table("analyses")
    op.drop_table("documents")
    op.drop_table("users")
