"""Auth-token tables: refresh_tokens, email_verification_tokens, password_reset_tokens.

Revision ID: 0002
Revises: 0001

Hand-written (not autogenerated): sha256 token hashes (CHAR(64)), rotation columns
(family_id, replaced_by_hash) for refresh reuse-detection, consumed_at markers for
single-use tokens. All owner FKs CASCADE (account delete purges sessions/tokens).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CREATED = sa.Column(
    "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
)


def _uuid_pk() -> sa.Column:
    return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True)


def _owner_fk() -> sa.Column:
    return sa.Column(
        "owner_id",
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )


def upgrade() -> None:
    op.create_table(
        "refresh_tokens",
        _uuid_pk(),
        _owner_fk(),
        sa.Column("token_hash", sa.CHAR(64), nullable=False, unique=True),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("replaced_by_hash", sa.CHAR(64)),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        sa.Column("user_agent", sa.String(255)),
        sa.Column("ip_hash", sa.CHAR(64)),
        _CREATED,
    )
    op.create_index("ix_refresh_tokens_owner", "refresh_tokens", ["owner_id"])
    op.create_index("ix_refresh_tokens_family", "refresh_tokens", ["family_id"])

    op.create_table(
        "email_verification_tokens",
        _uuid_pk(),
        _owner_fk(),
        sa.Column("token_hash", sa.CHAR(64), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True)),
        _CREATED,
    )
    op.create_index("ix_email_verification_tokens_owner", "email_verification_tokens", ["owner_id"])

    op.create_table(
        "password_reset_tokens",
        _uuid_pk(),
        _owner_fk(),
        sa.Column("token_hash", sa.CHAR(64), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True)),
        _CREATED,
    )
    op.create_index("ix_password_reset_tokens_owner", "password_reset_tokens", ["owner_id"])


def downgrade() -> None:
    op.drop_table("password_reset_tokens")
    op.drop_table("email_verification_tokens")
    op.drop_table("refresh_tokens")
