"""Segmentation support: analysis status + source text, nullable pre-detection
scores, requirement section/segmentation metadata (Stage 06).

Revision ID: 0003
Revises: 0002

Hand-written (not autogenerated). Rationale (docs/DATABASE_SCHEMA.md §3.2/§3.3):
Stage 06 persists SEGMENTED analyses before any detection exists, so `score` /
`band` (analysis + requirement level) become NULL-until-scored, `analyses`
gains a pipeline `status` plus the normalized `source_text` (re-segmentation
of stored text reproduces identical segments), and `requirements` gains the
heading-derived `section` path plus a `segmentation` JSONB evidence block
(strategy, confidence, offsets, line refs).

Data plan: no scored rows can exist before Stage 07 (no earlier writer), so
every pre-existing analyses/requirements row (dev/test only) already satisfies
the relaxed nullability; new columns backfill via server default (`status`) or
NULL. Downgrade DELETES unscored analyses (cascades to their requirements) —
acceptable pre-release data loss, documented here.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "analyses",
        sa.Column("status", sa.String(16), nullable=False, server_default="segmented"),
    )
    op.create_check_constraint("ck_analyses_status", "analyses", "status IN ('segmented')")
    op.add_column("analyses", sa.Column("source_text", sa.Text))
    op.alter_column("analyses", "score", existing_type=sa.SmallInteger, nullable=True)
    op.alter_column("analyses", "band", existing_type=sa.String(16), nullable=True)

    op.add_column("requirements", sa.Column("section", sa.String(200)))
    op.add_column("requirements", sa.Column("segmentation", postgresql.JSONB))
    op.alter_column("requirements", "score", existing_type=sa.SmallInteger, nullable=True)


def downgrade() -> None:
    # Segmented-but-unscored rows cannot satisfy the restored NOT NULLs.
    op.execute(sa.text("DELETE FROM analyses WHERE score IS NULL"))
    op.alter_column("requirements", "score", existing_type=sa.SmallInteger, nullable=False)
    op.drop_column("requirements", "segmentation")
    op.drop_column("requirements", "section")
    op.alter_column("analyses", "band", existing_type=sa.String(16), nullable=False)
    op.alter_column("analyses", "score", existing_type=sa.SmallInteger, nullable=False)
    op.drop_column("analyses", "source_text")
    op.drop_constraint("ck_analyses_status", "analyses", type_="check")
    op.drop_column("analyses", "status")
